title: INDOLOGY
description: Resources for Indological scholarship
plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
#
header_pages:
  - pages/about.md
  - pages/contact.md
  - pages/management-committee.md
  - pages/archives.md
  - pages/guidelines.md
  - pages/subscribe.md
  - pages/links.md
#
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true
#
theme: minima
