title: 
description: 
plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
#
header_pages:
  - pages/about.md
#
theme: minima
